spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5433/payment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true

server:
  port: 8002