spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/payment_db?authSource=admin

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

liquibase:
  enabled: true
  change-log: classpath:db.changelog/db.changelog-master.yaml
  url: mongodb://localhost:27017/payment_db


server:
  port: 8002
